"""Contract tests for the network configuration generator.

The tool under test is ``scripts/gen-network.py``: it reads a tfvars file
through the shared node parser and writes one systemd-networkd pair per node
into a target directory:

- ``k8s-<node>.netdev`` — a ``[NetDev]`` section with ``Name=k8s-<node>``
  and ``Kind=tap``
- ``k8s-<node>.network`` — a ``[Match]`` section with ``Name=k8s-<node>``
  plus a ``[Network]`` section with ``Bridge=k8sbr0``

A pair is written for the control-plane node and every worker. The output
directory is created (parents included) and rebuilt from scratch on every
run, so stale or unrelated content never lingers, and the generated bytes are
deterministic across runs and output locations. The CLI takes ``--tfvars
<path>`` and ``--output-dir <path>``; a missing or malformed tfvars file
exits non-zero with a message on stderr. Tests invoke the CLI as a subprocess
from the repo root and only ever write into pytest's ``tmp_path``. Fixtures
in ``tests/fixtures/`` are shared with the parser tests; ``example.tfvars``
(cp1 + w1 + w2) is the canonical input.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR = REPO_ROOT / "scripts" / "gen-network.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures"

EXPECTED_NODES = ["cp1", "w1", "w2"]
EXPECTED_FILES = [
    f"k8s-{node}.{ext}" for node in EXPECTED_NODES for ext in ("netdev", "network")
]


def run_generator(tfvars: Path, output_dir: Path) -> subprocess.CompletedProcess[str]:
    """Run scripts/gen-network.py in the repo venv with the given arguments."""
    return subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--tfvars",
            str(tfvars),
            "--output-dir",
            str(output_dir),
        ],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
        timeout=30,
        check=False,
    )


def netdev_content(node: str) -> str:
    """Expected .netdev document for a node, byte for byte."""
    return f"[NetDev]\nName=k8s-{node}\nKind=tap\n"


def network_content(node: str) -> str:
    """Expected .network document for a node, byte for byte."""
    return f"[Match]\nName=k8s-{node}\n\n[Network]\nBridge=k8sbr0\n"


def expected_example_output() -> dict[str, bytes]:
    """Map of file name to expected bytes for the canonical 3-node input."""
    expected: dict[str, bytes] = {}
    for node in EXPECTED_NODES:
        expected[f"k8s-{node}.netdev"] = netdev_content(node).encode("utf-8")
        expected[f"k8s-{node}.network"] = network_content(node).encode("utf-8")
    return expected


def output_bytes(output_dir: Path) -> dict[str, bytes]:
    """Map of file name to bytes for every regular file in the output dir."""
    return {
        entry.name: entry.read_bytes()
        for entry in sorted(output_dir.iterdir())
        if entry.is_file()
    }


def test_generate_example_produces_exact_file_set(tmp_path: Path) -> None:
    output_dir = tmp_path / "generated" / "network"
    proc = run_generator(FIXTURES / "example.tfvars", output_dir)

    assert proc.returncode == 0
    assert proc.stderr == ""
    assert sorted(entry.name for entry in output_dir.iterdir()) == EXPECTED_FILES


def test_generate_example_files_are_byte_exact(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"
    proc = run_generator(FIXTURES / "example.tfvars", output_dir)

    assert proc.returncode == 0
    assert output_bytes(output_dir) == expected_example_output()


def test_two_consecutive_runs_produce_identical_bytes(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"

    first = run_generator(FIXTURES / "example.tfvars", output_dir)
    assert first.returncode == 0
    first_output = output_bytes(output_dir)

    second = run_generator(FIXTURES / "example.tfvars", output_dir)
    assert second.returncode == 0
    assert output_bytes(output_dir) == first_output


def test_generated_bytes_do_not_depend_on_output_location(tmp_path: Path) -> None:
    first_dir = tmp_path / "a"
    second_dir = tmp_path / "b"

    first = run_generator(FIXTURES / "example.tfvars", first_dir)
    second = run_generator(FIXTURES / "example.tfvars", second_dir)

    assert first.returncode == 0
    assert second.returncode == 0
    assert output_bytes(first_dir) == output_bytes(second_dir)


def test_stale_file_for_node_not_in_tfvars_is_removed(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"
    first = run_generator(FIXTURES / "example.tfvars", output_dir)
    assert first.returncode == 0

    stale = output_dir / "k8s-w9.netdev"
    stale.write_text(netdev_content("w9"), encoding="utf-8")
    assert stale.is_file()

    second = run_generator(FIXTURES / "example.tfvars", output_dir)
    assert second.returncode == 0
    assert not stale.exists()
    assert sorted(entry.name for entry in output_dir.iterdir()) == EXPECTED_FILES


def test_output_dir_is_recreated_from_scratch(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"
    output_dir.mkdir(parents=True)
    (output_dir / "stale.txt").write_text("orphan", encoding="utf-8")
    (output_dir / "k8s-w9.network").write_text(network_content("w9"), encoding="utf-8")
    (output_dir / "junk-subdir").mkdir()
    (output_dir / "junk-subdir" / "junk.bin").write_bytes(b"\x00\x01")

    proc = run_generator(FIXTURES / "example.tfvars", output_dir)

    assert proc.returncode == 0
    assert sorted(entry.name for entry in output_dir.iterdir()) == EXPECTED_FILES
    assert not (output_dir / "junk-subdir").exists()


def test_missing_tfvars_exits_nonzero_with_message(tmp_path: Path) -> None:
    missing = tmp_path / "does-not-exist.tfvars"
    proc = run_generator(missing, tmp_path / "network")

    assert proc.returncode != 0
    assert proc.stdout == ""
    assert str(missing) in proc.stderr


def test_malformed_tfvars_exits_nonzero_with_message(tmp_path: Path) -> None:
    proc = run_generator(FIXTURES / "malformed.tfvars", tmp_path / "network")

    assert proc.returncode != 0
    assert proc.stdout == ""
    assert proc.stderr != ""
    # The failure must come from parsing the file, not from the tool itself
    # being absent on disk.
    assert "No such file" not in proc.stderr


def test_non_w_prefixed_worker_gets_generated_pair(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"
    proc = run_generator(FIXTURES / "non_w_name.tfvars", output_dir)

    assert proc.returncode == 0
    assert sorted(entry.name for entry in output_dir.iterdir()) == [
        "k8s-cp1.netdev",
        "k8s-cp1.network",
        "k8s-gpu-1.netdev",
        "k8s-gpu-1.network",
        "k8s-w2.netdev",
        "k8s-w2.network",
    ]


def test_empty_workers_generates_only_control_plane_pair(tmp_path: Path) -> None:
    output_dir = tmp_path / "network"
    proc = run_generator(FIXTURES / "empty_workers.tfvars", output_dir)

    assert proc.returncode == 0
    assert sorted(entry.name for entry in output_dir.iterdir()) == [
        "k8s-cp1.netdev",
        "k8s-cp1.network",
    ]
