FROM docker.io/library/golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY handlers/ handlers/
COPY dbpool/ dbpool/
COPY metrics/ metrics/
COPY main.go .
RUN CGO_ENABLED=0 go build -o api-server .

FROM scratch
COPY --from=builder /app/api-server /api-server
EXPOSE 8080
ENTRYPOINT ["/api-server"]
