FROM docker.io/library/golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY main.go .
COPY query/ ./query/
COPY pool/ ./pool/
COPY metrics/ ./metrics/
RUN CGO_ENABLED=0 go build -o db-simulator .

FROM scratch
COPY --from=builder /app/db-simulator /db-simulator
EXPOSE 8080
ENTRYPOINT ["/db-simulator"]
