# k8labs base image build variables
# Usage: packer build -var-file=vars.pkrvars.hcl .
#
# Override any value here or pass -var="key=value" on the CLI.

# Fedora 41 Everything netinstall ISO (local modified copy)
# Generated by: make prepare-iso (from the official Fedora download)
iso_url      = "file:///home/eryoma/projects/k8labs/build/fedora-boot.iso"
iso_checksum = "none"

# SSH credentials for Packer provisioning (matches kickstart rootpw)
ssh_username = "root"
ssh_password = "k8sosroot"

# VM hardware
vm_name       = "k8labs-base"
vm_cpu_cores  = 2
vm_memory     = 2048
vm_disk_size  = 10240

# Output
output_directory = "../build/base"

# Boot command uses default (kickstart-based install)
# boot_command is defined with a sensible default in variables.pkr.hcl
