#!/usr/bin/env bash
# runtime-tfvars.sh — Emit build/runtime.tfvars (inputs for terraform/runtime).
#
# Reads the phase-A tofu output `tofu -chdir=terraform output -json nodes`
# (one entry per node: name/mac/role), resolves each node's current IP from the
# DHCP lease files via scripts/vm-ip.sh, and writes the
# terraform/runtime input contract consumed by `make configure`:
#   cp_ip, node_ips, node_roles, ssh_user, ssh_private_key.
#
# Fails loudly (exit 1) if any node lacks a lease — phase B embeds node IPs in
# certs/kubeconfigs/etcd.conf, so a missing IP must never proceed.
#
# Usage: scripts/runtime-tfvars.sh [output-path]
#   output-path defaults to build/runtime.tfvars at the repo root.

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"

# Output path, defaulting to the repo-root build/runtime.tfvars.
OUTPUT_PATH="${1:-${REPO_ROOT}/build/runtime.tfvars}"

# Phase-B push identity: the same key wait-ssh relies on. Overridable via env.
SSH_USER="${SSH_USER:-root}"
SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY:-${HOME}/.ssh/id_ed25519}"

cd -- "${REPO_ROOT}"

# --- Load the node list (name/mac/role) from the phase-A tofu output --------

nodes_json="$(tofu -chdir=terraform output -json nodes)" || {
    echo "ERROR: 'tofu -chdir=terraform output -json nodes' failed" >&2
    echo "  Phase A must be applied first (make deploy) to expose the node list." >&2
    exit 1
}
node_count="$(jq 'length' <<<"${nodes_json}")" || {
    echo "ERROR: 'tofu -chdir=terraform output -json nodes' did not return valid JSON" >&2
    exit 1
}
if [[ "${node_count}" -eq 0 ]]; then
    echo "ERROR: tofu output 'nodes' is empty — no cluster nodes to configure" >&2
    exit 1
fi

# --- Resolve each node's IP from the DHCP lease files -----------------------

declare -A ip_by_name=()
declare -A role_by_name=()
cp_ip=""

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

# One compact JSON object per line; read from a file so the loop sees exactly
# the node entries (no trailing blank line) and no process substitution.
jq -c '.[]' <<<"${nodes_json}" >"${tmpdir}/nodes.jsonl"

while IFS= read -r entry; do
    name="$(jq -r '.name' <<<"${entry}")"
    mac="$(jq -r '.mac' <<<"${entry}")"
    role="$(jq -r '.role' <<<"${entry}")"
    # tofu emits role "control_plane"; the terraform/runtime contract uses
    # "control-plane" (terraform/runtime/variables.tf, push.tf).
    if [[ "${role}" = "control_plane" ]]; then
        role="control-plane"
    fi

    ip="$(scripts/vm-ip.sh "${mac}")" || {
        echo "ERROR: no DHCP lease found for node '${name}' (MAC ${mac})" >&2
        echo "  Wait for DHCP (make wait-ips) and re-run; check network/k8sbr0.network" >&2
        echo "  and the systemd-networkd/dnsmasq lease files." >&2
        exit 1
    }

    ip_by_name["${name}"]="${ip}"
    role_by_name["${name}"]="${role}"
    if [[ -z "${cp_ip}" && "${role}" = "control-plane" ]]; then
        cp_ip="${ip}"
    fi
done <"${tmpdir}/nodes.jsonl"

if [[ -z "${cp_ip}" ]]; then
    echo "ERROR: no control-plane node found in tofu output 'nodes'" >&2
    exit 1
fi

# --- Render and atomically write build/runtime.tfvars -----------------------

# Deterministic (sorted) node order for repeatable tfvars output.
printf '%s\n' "${!ip_by_name[@]}" | sort >"${tmpdir}/names.txt"
mapfile -t node_names <"${tmpdir}/names.txt"
name_pad=0
for name in "${node_names[@]}"; do
    len="${#name}"
    if (( len > name_pad )); then
        name_pad="${len}"
    fi
done

{
    echo "# Generated by scripts/runtime-tfvars.sh — terraform/runtime inputs (phase B)."
    echo "# Regenerate with: make runtime-tfvars"
    echo ""
    echo "cp_ip = \"${cp_ip}\""
    echo ""
    echo "node_ips = {"
    for name in "${node_names[@]}"; do
        printf '  %-*s = "%s"\n' "${name_pad}" "${name}" "${ip_by_name[${name}]}"
    done
    echo "}"
    echo ""
    echo "node_roles = {"
    for name in "${node_names[@]}"; do
        printf '  %-*s = "%s"\n' "${name_pad}" "${name}" "${role_by_name[${name}]}"
    done
    echo "}"
    echo ""
    echo "ssh_user = \"${SSH_USER}\""
    echo "ssh_private_key = \"${SSH_PRIVATE_KEY}\""
} >"${tmpdir}/runtime.tfvars"

mkdir -p "$(dirname -- "${OUTPUT_PATH}")"
mv -- "${tmpdir}/runtime.tfvars" "${OUTPUT_PATH}"
trap - EXIT

if [[ ! -f "${SSH_PRIVATE_KEY}" ]]; then
    echo "WARNING: SSH private key '${SSH_PRIVATE_KEY}' not found — phase-B push (ssh/scp) will fail" >&2
fi

echo "Generated ${OUTPUT_PATH} (${node_count} nodes, cp_ip=${cp_ip})"
