FROM docker.io/library/golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod main.go .
RUN CGO_ENABLED=0 go build -o cpu-burner .

FROM scratch
COPY --from=builder /app/cpu-burner /cpu-burner
EXPOSE 8080
ENTRYPOINT ["/cpu-burner"]
